CREATE SCHEMA IF NOT EXISTS productList DEFAULT CHARACTER SET utf8 ;
USE productList;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(60) NOT NULL,
  price DECIMAL(19,2),
  category VARCHAR(40),
  discount DECIMAL(19,2),
  description VARCHAR(200) NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1002;

CREATE TABLE IF NOT EXISTS shopping_cart (
  id BIGINT NOT NULL AUTO_INCREMENT,
  customer_name VARCHAR(60),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1002;

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT NOT NULL AUTO_INCREMENT,
  product_id BIGINT,
  count INT,
  shopping_cart_id BIGINT,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1002;

