CREATE SCHEMA IF NOT EXISTS productList DEFAULT CHARACTER SET utf8 ;
USE productList;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(60) NOT NULL,
  price DECIMAL(19,2),
  category VARCHAR(40),
  discount DECIMAL(19,2),
  description VARCHAR(200) NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1002;

CREATE TABLE IF NOT EXISTS shoppingCart (
  id BIGINT NOT NULL AUTO_INCREMENT,
  customerName VARCHAR(60),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1002;

CREATE TABLE IF NOT EXISTS orderItems (
  id BIGINT NOT NULL AUTO_INCREMENT,
  productId BIGINT,
  count INT,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1002;

