CREATE SCHEMA IF NOT EXISTS productList DEFAULT CHARACTER SET utf8 ;
USE productList;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(60) NOT NULL,
  price DOUBLE,
  category VARCHAR(40),
  discount DOUBLE,
  description VARCHAR(200) NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1002;